### ISSUE TITLE
Blindness to reading LDIFs that "blank out" or set null value for an attribute.

### ISSUE THREAD

**Issue by dotHTM** [perl-ldap/perl-ldap#52]
# Description

LDIFs that contain an attribute that is modified to be a null or blank value are not communicated through this library.

Since LDIFs are meant for incremental changes, only the changed attributes are included, so there's no way to assume that a particular attribute exists in the source LDIF, and no way to assume that it has a null value.

# Example

Consider the following, for a sample LDIF file:
```
dn: uid=asdf1234,ou=people,dc=entdir,dc=example,dc=com
changetype: modify
replace: someAttribute
-
replace: anotherAttribute
anotherAttribute: hello world
-
replace: personLastUpdateTime
personLastUpdateTime: 20180827101540Z
-
```

A sample script, based on the example code from [NET::LDAP::LDIF](https://metacpan.org/pod/distribution/perl-ldap/lib/Net/LDAP/LDIF.pod):

```perl
#!/usr/bin/perl

use feature ':5.16';
use strict;
use warnings;
use Data::Dumper;

use Net::LDAP::LDIF;

my $ldif = Net::LDAP::LDIF->new( "sample.ldif", "r", onerror => 'undef' );

while ( not $ldif->eof() ) {
    my $entry = $ldif->read_entry();
    if ( $ldif->error() ) {
        print "Error msg: ",    $ldif->error(),       "\n";
        print "Error lines:\n", $ldif->error_lines(), "\n";
    }
    else {
        # do stuff
        say "dump";
        say $entry->dump;
        say "----";
        say "testing key-value:\n";
        exists_and_value( $entry, 'someAttribute' );
        exists_and_value( $entry, 'anotherAttribute' );
        exists_and_value( $entry, 'personLastUpdateTime' );
        say "----";
        say "attrs";
        say Dumper $entry->{attrs};
    }
}
$ldif->done();

sub exists_and_value {
    my ( $entry, $key ) = @_;
    say "  - $key";
    say "    - exists: '" . ( $entry->exists($key) ) . "'";
    say "    - value: '" . ( $entry->get_value($key) || '' ) . "'";
    return "function_name: wip, placeholder";
}    ##    exists_and_value
```

Results demonstrate that while the `someAttribute` field was set to a blank/null value, the library does not show this effect.
```
dump
------------------------------------------------------------------------
dn:uid=asdf1234,ou=people,dc=entdir,dc=example,dc=com

    anotherAttribute: hello world
personLastUpdateTime: 20180827101540Z

----
testing key-value:

  - someAttribute
    - exists: ''
    - value: ''
  - anotherAttribute
    - exists: '1'
    - value: 'hello world'
  - personLastUpdateTime
    - exists: '1'
    - value: '20180827101540Z'
----
attrs
$VAR1 = {
          'personlastupdatetime' => [
                                      '20180827101540Z'
                                    ],
          'anotherattribute' => [
                                  'hello world'
                                ]
        };

[Finished in 0.1s]
```

# Suggested fix

It would be important to distinguish between null values and empty-strings, and so I feel the existing behavior of `get_value` is fine.

Instead, `exists` should be modified to return `1` on those null'ed out values, and the `->{attrs}` property should be updated to include those keys, with an empty array-ref to indicate no value set.

An argument might be made to change `get_value` to return an empty array or empty array-ref when the value is null for a given attribute (that *is part* of the LDIF), but I see where such a similar suggestion was decided against (#46).

**Comment by coudot** [comment]
As far as I know, we can't have empty values in LDIF. If you want to delete an attribute, you don't use `replace` but `delete`. Are there other use cases where you need to manage empty values?

**Comment by dotHTM** [comment]
The background of my work is that my organization has an LDAP server for authentication, etc. For reasons, my team needs an independent cache of some of that data, which we take a full sync via direct ldap query, and keep up to date via incremental LDIF processing we receive via scp from the LDAP managers.

We do this primarily in case the LDAP server does down or one of it's many APIs goes down. We just get the changes when it comes back up, and everyone uses our services in the meantime without noticing that central LDAP was down or anything.

> As far as I know, we can't have empty values in LDIF. 

The LDIFs my group receives say otherwise. 

The sample I provided above is an anonymized version of an LDIF entry we've received, about 8k such value nullifications in the last 27 days using the same format:

```
dn: uid=asdf1234,ou=people,dc=entdir,dc=example,dc=com
changetype: modify
replace: someAttribute
-
replace: anotherAttribute
anotherAttribute: hello world
-
replace: personLastUpdateTime
personLastUpdateTime: 20180827101540Z
-
```

When I query the LDAP directly for the given dn, I get a result that is missing the above "blanked out" value (e.i. the key doesn't exist) and that is fine. It's the LDIF processing via this library that misses this change all together.

I have zero control on how the LDAP server is configured or how the LDIFs are delivered to my code. So advice about having a different verb come through isn't helpful.

*As far as I know*, the `delete` keyword is for signaling the dn is being deleted.

## Possible work around for my specific case

Instead of taking the data contained in the LDIFs from this library, I could just collect an array of the dn's in a batch of LDIFs, then parse for a unique set, and do individual LDAP queries on those users.

This defeats the purpose of incremental changes being logged and sent to us, relies on that LDAP service to be up all the time or developing a queuing solution to wait while it's down or if we get rate limited on queries.

**Comment by coudot** [comment]
> The LDIFs my group receives say otherwise

Indeed, I tested such LDIF with ldapmodify and it works.

> As far as I know, the delete keyword is for signaling the dn is being deleted.

No, the delete keywork deletes the entry if it used is the changetype. If the changetype is modify, then the delete keywork under it means the attribute is deleted. This is the standard way of deleting an attribute, instead of replacing it by a null value.

**Comment by dotHTM** [comment]
I’ll see if I can get my org’s ldap team to “do things right” but I can’t promise anything.

**Comment by marschap** [comment]
Hi @dotHTM 

I do not know what you want to achieve, but what you describe is not an error in perl-ldap, but a misconception on your part.

If you use the proper methods, then the data gets synchronized 1:1, of course including all the changes from the original LDIF file.

Proof:
After the line
`say Dumper $entry->{attrs};`
add a new line containing
`say say $entry->ldif(change => 1);`
and re-execute your script!
It will show a correct representation of your original LDIF input.

Explanation:
Per the RFC LDIF entries come in one of 2 varieties:
* _content entries_: they contain the contents: DN + attributes and their values.
  Those can always be correctly represented as complete, "static" LDAP entries. 
  perl-ldap stores them as Net::LDAP::Entry objects with all the attributes & values in the `attrs` hash.
* _change entries_: they contain the DN and a series of changes to the original entry: attribute changes, moddn, deletion, entry creation, .... 
Those change can - by definition - not represent complete, "static" LDAP entries, because they only describe the transformation from one state of the entry to a new state, but they do not contain the original state.
For them Net::LDAP::Entry objects contains only the attribute values added in the `attrs` hash, but in addition there is the `changes` hash that details the all changes to execute. And exactly this hash is used in the methods acting on the Net::LDAP::Entry object when writing the changes.

Yours was a change entry.
To get its changes synchronized to an LDAP server exactly as read from the LDIF, simply do
`$entry->update($ldap)`
where `$ldap` is the Net::LDAP object opened to the LDAP server.

Example of an LDIF change entry that can definitely not be represented by attributes:
`dn: cn=my,ou=sample,o=object`
`changetype: modify`
`delete: myattribute`
`myattribute: my old value`
`-`
This entry wants to delete the value `my old value` (and only this one) from `myattribute`.
I hope you agree that this value does not belong into the `attrs` hash of the Net::LDAP::Entry object.

To clarify some misunderstandings:
* LDAP attributes without a value, simply do not exist.
  Hence it is correct for them
  - that `exists()` returns FALSE
  - that they do not end up not in the `attrs` hash.
* as the documentation states Net::LDAP::Entry->dump() is a debugging tool [and not the best one].
  Don't use it in standard operation.

Best
Peter

**Comment by dotHTM** [comment]
Thank you for the clarification, the misconception extends to the previous author of my script.
